let mainTinyModel;const win=window;Ant.AxmlPanel=class extends Elements.ElementsPanel{constructor(){super('axml');this.registerRequiredCSS('elements/elementsTreeOutline.css');Ant.targetManager.addEventListener(Ant.TargetManager.Events.switchTarget,this.requestTargetWS,this);this.requestTargetWS();}
targetAdded(target,path){var domModel=Ant.TinyModel.fromTarget(target);if(!path)return;if(mainTinyModel)
this.modelRemoved(mainTinyModel);mainTinyModel=domModel;var treeOutline=new Ant.ElementsTreeOutline(domModel,true,true);treeOutline.setWordWrap(Common.moduleSetting('domWordWrap').get());treeOutline.wireToDOMModel();treeOutline.addEventListener(Elements.ElementsTreeOutline.Events.SelectedNodeChanged,this._selectedNodeChanged,this);treeOutline.addEventListener(Elements.ElementsTreeOutline.Events.ElementsTreeUpdated,this._updateBreadcrumbIfNeeded,this);new Elements.ElementsTreeElementHighlighter(treeOutline);this._treeOutlines=[treeOutline];domModel[Elements.ElementsTreeOutline._treeOutlineSymbol]=treeOutline;if(this.isShowing())
this.wasShown();}
targetRemoved(target){var domModel=Ant.TinyModel.fromTarget(target);if(!domModel)
return;}
modelRemoved(domModel){var treeOutline=Elements.ElementsTreeOutline.forDOMModel(domModel);if(!treeOutline)return;treeOutline.unwireFromDOMModel();this._treeOutlines.remove(treeOutline);treeOutline.element.remove();}
modelAdded(domModel,path,target){if(!path)return;if(mainTinyModel)
this.modelRemoved(mainTinyModel);mainTinyModel=domModel;var treeOutline=new Ant.ElementsTreeOutline(domModel,true,true);treeOutline.setWordWrap(Common.moduleSetting('domWordWrap').get());treeOutline.wireToDOMModel();treeOutline.addEventListener(Elements.ElementsTreeOutline.Events.SelectedNodeChanged,this._selectedNodeChanged,this);treeOutline.addEventListener(Elements.ElementsTreeOutline.Events.ElementsTreeUpdated,this._updateBreadcrumbIfNeeded,this);new Elements.ElementsTreeElementHighlighter(treeOutline);this._treeOutlines=[treeOutline];if(domModel.target().parentTarget()){this._treeOutlineHeaders.set(treeOutline,createElementWithClass('div','elements-tree-header'));this._targetNameChanged(domModel.target());}
if(this.isShowing())
this.wasShown();}
async requestTargetWS(){const current=Ant.targetManager.getCurrent();if(!current.model||!current.target||!current.path){return;}
const{path,model,target,}=current;this._target=target;this._tinyModel=model;this.targetAdded(target,path);SDK.targetManager.addModelListener(Ant.TinyModel,SDK.DOMModel.Events.DocumentUpdated,this._documentUpdatedEvent,this);await model.requestDocumentPromise();}};;Ant.StoragePanel=class extends UI.VBox{constructor(){super('storage');this.registerRequiredCSS('resources/resourcesPanel.css');this._target=SDK.targetManager.mainTarget();this.contentElement.classList.add('storage-view');const domStorageModel=this._target.model(Resources.DOMStorageModel);domStorageModel.enable();domStorageModel.storages().forEach(this._addDOMStorage.bind(this));domStorageModel.addEventListener(Resources.DOMStorageModel.Events.DOMStorageAdded,this._domStorageAdded,this);domStorageModel.addEventListener(Resources.DOMStorageModel.Events.DOMStorageRemoved,this._domStorageRemoved,this);this._domStorageView=null;}
_addDOMStorage(domStorage){if(!domStorage._isLocalStorage)return;this.showStorage(domStorage);}
_domStorageAdded(event){var domStorage=(event.data);this._addDOMStorage(domStorage);}
_domStorageRemoved(event){var domStorage=(event.data);this._removeDOMStorage(domStorage);}
_removeDOMStorage(domStorage){var treeElement=this._domStorageTreeElements.get(domStorage);if(!treeElement)
return;var wasSelected=treeElement.selected;var parentListTreeElement=treeElement.parent;parentListTreeElement.removeChild(treeElement);if(wasSelected)
parentListTreeElement.select();this._domStorageTreeElements.remove(domStorage);}
showView(view){view.show(this.contentElement);}
showStorage(domStorage){if(!domStorage)
return null;if(!this._domStorageView)
this._domStorageView=new Resources.DOMStorageItemsView(domStorage);else
this._domStorageView.setStorage(domStorage);this.showView(this._domStorageView);}};Ant.StoragePanel.ResourceRevealer=class{reveal(resource){if(!(resource instanceof SDK.Resource))
return Promise.reject(new Error('Internal error: not a resource'));var panel=Resources.ResourcesPanel._instance()._sidebar;return UI.viewManager.showView('resources').then(panel.showResource.bind(panel,resource));}};;Ant.DataPanel=class extends UI.VBox{constructor(){super('data');this.contentElement.classList.add('data-view');}};;Ant.AcssModel=class extends SDK.CSSModel{constructor(target){super(target);this._agent=target.cssAgent();}};;Ant.ElementsTreeOutline=class extends Elements.ElementsTreeOutline{static forDOMModel(tinyModel){return tinyModel[Elements.ElementsTreeOutline._treeOutlineSymbol]||null;}
_updateModifiedParentNode(node){const self=this;var parentTreeElement=this.findTreeElement(node);function getData(children){return children.map(child=>({backendNodeId:child._backendNodeId,nodeId:child.id,}));}
async function callback({data}){let j=0;const agent=Ant.targetManager.getCurrentTarget().domAgent();if(node._localName==='picker-view-column')
return this._updateChildren(parentTreeElement);if(node._localName==='picker-view'){await agent.requestChildNodes(node.id,3);if(node._children[0]._localName!=='picker-view-column'){for(const i in node._children){node._children[i]._attributes=[];node._children[i]._attributesMap={};node._children[i]._localName='picker-view-column';node._children[i]._nodeName='picker-view-column'.toUpperCase();node._children[i]._children=node._children[i]._children[2]._children;node._children[i]._children.forEach(child=>{child._attributes=[];child._attributesMap={};child._localName='picker-view-item';child._nodeName='picker-view-item'.toUpperCase();});}}
return this._updateChildren(parentTreeElement);}
if(node._localName==='swiper'){await agent.requestChildNodes(node.id,4);try{const ul=Ant.findUL(node);node._children=ul._children.map(child=>{child._attributes=[];child._attributesMap={};child._localName='swiper-item';child._nodeName='swiper-item'.toUpperCase();return child;});}catch(e){}
return this._updateChildren(parentTreeElement);}
for(const i in node._children){let child=node._children[i];if(!child)continue;if(data&&data[j]&&!child._nodeValue){child=Ant.combineNativeAndReactDom(child,data[j++]);if(Ant.spanTags.has(child._localName)||(child._localName==='label'&&child._textChildren)){let textNode;if(child._localName==='text'||(child._localName==='label'&&child._textChildren)){await agent.requestChildNodes(child.id,1);textNode=child.children()[1];}else{const id=await agent.querySelector(child.id,'span');textNode=Ant.DOMNode.create(Ant.targetManager.getCurrentModel(),child._document,false,{nodeId:id+1,backendNodeId:id,nodeValue:child._textValue,nodeType:3,childNodeCount:0,localName:'',nodeName:'#text',});}
if(textNode){child.firstChild=textNode;child._children=[textNode];child.lastChild=textNode;}}}}
this._updateChildren(parentTreeElement);}
if(parentTreeElement){parentTreeElement.setExpandable(this._hasVisibleChildren(node));parentTreeElement.updateTitle(this._updateRecordForHighlight(node));if(parentTreeElement.populated){node.getChildNodes(children=>{if(!children)return;Ant.makeProxyPromiseOnce('setChildNodeIdOnce',{parentId:node.id,nodeType:node._localName,payloads:getData(children)},callback.bind(self));});}}}
_updateChildren(treeElement){if(!treeElement.isExpandable()){var selectedTreeElement=treeElement.treeOutline.selectedTreeElement;if(selectedTreeElement&&selectedTreeElement.hasAncestor(treeElement))
treeElement.select(true);treeElement.removeChildren();return;}
console.assert(!treeElement.isClosingTag());this._innerUpdateChildren(treeElement);}};Ant.combineNativeAndReactDom=(dom,data)=>{const obj=[];const objMap={};dom._localName=data.name;dom._nodeName=data.name.toUpperCase();Object.keys(data.props||{}).forEach(key=>{let value=data.props[key];const keyValue={};keyValue.value='';keyValue.name=key;if(key.match(/^_/)){dom[key]=value;return;}
if(typeof value==='string'){keyValue.value=value;}else if(typeof value==='object'){Object.keys(value).forEach(property=>{keyValue.value+=`${property}: ${value[property]};`;});}else{keyValue.value+=`${String(value)}`;}
keyValue._node=dom;obj.push(keyValue);objMap[key]=keyValue;});dom._attributes=obj;dom._attributesMap=objMap;return dom;};Ant.findUL=element=>{if(element._localName==='ul')return element;return Ant.findUL(element._children[0]);};Ant.spanTags=new Set(['button','text']);;